// Generated by CoffeeScript 1.3.3

/*
Coffee file for Geremy Good
*/


(function() {

  $('document').ready(function() {
    var navigation, viewportHeight;
    navigation = $('nav');
    viewportHeight = $(window).height();
    $(window).scroll(function() {
      var pixels;
      pixels = $(window).scrollTop();
      return $('section').each(function() {
        var $this, color, current, height, offset;
        $this = $(this);
        offset = $this.offset();
        height = $this.outerHeight();
        if (pixels + (viewportHeight / 2) > offset.top && pixels + (viewportHeight / 2) < offset.top + height) {
          current = $this.index();
          $this.addClass('active');
          $('nav ol li:nth-of-type(' + current + ')').addClass('active');
          $('nav ol li:not(:nth-of-type(' + current + '))').removeClass('active');
          color = $('li.active a').css('background-color');
          return $('html').css({
            'border-color': color
          });
        } else {
          return $this.removeClass('active');
        }
      });
    });
    return $(document).bind('keydown', function(e) {
      var current;
      if (e.keyCode === 38) {
        current = $('section.active').index();
        current = parseInt(current);
        return $('nav ol li:nth-of-type(' + (current - 1) + ') a').click();
      } else if (e.keyCode === 40) {
        current = $('section.active').index();
        current = parseInt(current);
        return $('nav ol li:nth-of-type(' + (current + 1) + ') a').click();
      }
    });
  });

}).call(this);
