// Generated by CoffeeScript 1.3.3

/*
Coffee file for Geremy Good

Purpose of this file is to determine what the current view is.
*/


(function() {

  $(function() {
    return $('section').each(function(e) {
      section[i] = this.id;
      i++;
      return console.log(section[1]);
    });
  });

}).call(this);
